//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsRoverTracking.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rover
    {
        public string Id { get; set; }
        public int PosX { get; set; }
        public int PosY { get; set; }
        public int Orientation { get; set; }
    }
}
